name: 编译内核

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: tem423/kernel_build_action@main
        with:
          kernel-url: https://github.com/tem423/android_kernel_lenovo_tb371fc
          kernel-branch: lineage
          config: vendor/tb371fc_defconfig
          arch: arm64
          android-version: 11
          ccache: false
          ksu: false
          ksu-version: v0.9.5
          # aosp
          # aosp-gcc: true
          # aosp-clang: true
          # aosp-clang-version: r383902
          # ndk
          # android-ndk: true
          # android-ndk-version:         r23b
          other-clang-url: https://github.com/sticpaper/Snapdragon-LLVM-ARM-Compiler-10.0.7-for-Android-NDK
          other-clang-branch: main
          anykernel3: true
          bootimg-url: https://github.com/tem423/android_kernel_lenovo_tb371fc/releases/download/originalboot/boot.img
          release: false
          access-token: ${{ secrets.GITHUB_TOKEN }}
